'''
THIS .PY FILE SHOULD BE THE SAME FOR ALL PLUGINS.
A CHANGE TO THIS .PY IN ONE OF THE PLUGINS SHOULD BE COPPY-PASTED TO ALL THE OTHER ONES
'''

def get_suffixes():
    return ["_SELECT_FOLDER", "_SELECT_FILE", "_SELECT_LAYER", "_COMMENT", "_TOOLTIP", "_RADIO", "_VIDEO", "_CHILDREN"]